### ISSUE TITLE
[Question] Bukkit API for MCRealistic (Bukkit Page) Plugin

### ISSUE THREAD

**Issue by R4zzer** [SamB440/MCRealistic#5]
What API use the Plugin? I want to translate it.

**Comment by SamB440** [comment]
Hi, may I ask why you are using 1.8 still? I have also been wanting to add an API to McRealisticPlus for a while now. I may do that soon. If I want to make my plugin compatible with all versions, I may have to use an API as I've never looked into reflection before, and it seems pretty complex. I'm going to ask the people on Spigot to see how I can make it compatible with all versions you can use MCRealisticPlus.

**Comment by R4zzer** [comment]
Okay! Then I will wait for your 1.8 Release. :)
